### ISSUE TITLE
From private key to public key -> BTC address

### ISSUE THREAD

**Issue by FAlbanni** [blockstack/pybitcoin#52]
BTC address: '1DcKRUKGKt5bwi3mtFNNEuufp6DFxEBR9C'
Private Key: 'fb8c80c0d5af5c14e3b19265bf4c1fef00a457933b2022d145694a541549acaf'

I have a private key and I want to get the BTC address, this is what I do:

> from pybitcoin import BitcoinPrivateKey
> private_key = BitcoinPrivateKey('fb8c80c0d5af5c14e3b19265bf4c1fef00a457933b2022d145694a541549acaf')
> private_key.public_key().address()

output: '1DBkszCUoFuXEJE1ynbteVLYZcuUjjKChS'

what I am doing wrong?

**Comment by shea256** [comment]
Hey @FAlbanni this should work:

```python
>>> from pybitcoin import BitcoinPrivateKey
>>> private_key = BitcoinPrivateKey('fb8c80c0d5af5c14e3b19265bf4c1fef00a457933b2022d145694a541549acaf', compressed=True)
>>> private_key.public_key().address()
'1DcKRUKGKt5bwi3mtFNNEuufp6DFxEBR9C'
```

**Comment by FAlbanni** [comment]
compressed=True
of course
thank you!!!
